In [1]:
import tensorflow as tf
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

C:\Users\user\anaconda3\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


In [2]:
# Features: 2D points
X = np.array([
    [1,2], [2,1], [2,2],
    [6,5], [7,6], [6,7],
    [12,10], [13,11], [11,12]
], dtype=np.float32)

# Labels: 3 classes
y = np.array([0,0,0, 1,1,1, 2,2,2])

In [3]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

In [4]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [5]:
num_classes = 3

model = tf.keras.Sequential([

    tf.keras.layers.Dense(64, activation='relu',
                          input_shape=(X_train.shape[1],)),

    tf.keras.layers.Dense(32, activation='relu'),

    tf.keras.layers.Dense(16, activation='relu'),

    # Output layer for multiclass
    tf.keras.layers.Dense(num_classes, activation='softmax')
])


C:\Users\user\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

In [7]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 64)                  │             192 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 3)                   │              51 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,851 (11.14 KB)

 Trainable params: 2,851 (11.14 KB)

 Non-trainable params: 0 (0.00 B)

In [8]:
history = model.fit(
    X_train,
    y_train,
    epochs=300,
    batch_size=4,
    validation_data=(X_test, y_test),
    verbose=1
)

Epoch 1/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 260ms/step - accuracy: 0.5000 - loss: 1.0832 - val_accuracy: 0.6667 - val_loss: 0.8929
Epoch 2/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.6667 - loss: 0.8771 - val_accuracy: 0.6667 - val_loss: 0.7591
Epoch 3/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.6667 - loss: 0.7584 - val_accuracy: 0.6667 - val_loss: 0.6114
Epoch 4/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6667 - loss: 0.5881 - val_accuracy: 0.6667 - val_loss: 0.4880
Epoch 5/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.6667 - loss: 0.4897 - val_accuracy: 0.6667 - val_loss: 0.4117
Epoch 6/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.8333 - loss: 0.4224 - val_accuracy: 1.0000 - val_loss: 0.3586
Epoch 7/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.8333 - loss: 0.3669 - val_accuracy: 1.0000 - val_loss: 0.3172
Epoch 8/300
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.8333 - loss: 0.3448 - val_accuracy: 1.0000 - val_loss

In [9]:
loss, acc = model.evaluate(X_test, y_test)
print("Test Loss:", loss)
print("Test Accuracy:", acc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 2.0623e-05
Test Loss: 2.062267594737932e-05
Test Accuracy: 1.0


In [10]:
probs = model.predict(X_test)
print("Probabilities:\n", probs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step
Probabilities:
 [[4.7256692e-15 3.8403581e-08 1.0000000e+00]
 [9.9999428e-01 5.7726916e-06 1.8151579e-11]
 [1.2871621e-05 9.9994385e-01 4.3259570e-05]]


In [11]:
pred_classes = np.argmax(probs, axis=1)
print("Predicted classes:", pred_classes)
print("True classes:", y_test)

Predicted classes: [2 0 1]
True classes: [2 0 1]
